---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r echo=TRUE}
     ## Unpack and load our data set
     if(!file.exists("./data")){dir.create("./data")}
     if(!file.exists("./data/activity.csv")){
          unzip("./activity.zip",exdir = "./data")}
     activityData <- read.csv("./data/activity.csv")
     
     ## Tidy/transform our data so that its more suitable for analysis
     date <- strptime(activityData$date, format = "%Y-%m-%d")
     date <- format(date, "%Y/%m/%d")
     activityData$date <- date
     activityData <- cbind(activityData[,2:3],activityData$steps)  ## Reorder variables
```


## What is mean total number of steps taken per day?

After removing rows with missing data, our mean steps per day is `10766.19`.

```{r echo=TRUE}
     activityDataNoNAs <- na.omit(activityData)
     stepsPerDay <- aggregate(activityDataNoNAs$steps, by=list(date = activityDataNoNAs$date), FUN=sum)
     totalStepsPerDay <- sum(stepsPerDay$x)
     medianStepsPerDay <- median(stepsPerDay$x)
     meanStepsPerDay <- mean(stepsPerDay$x)
```

Historgram of mean steps per day
(https://github.com/trevorsaurus9000/RepData_PeerAssessment1/blob/master/meanStepsPerDay.png)

```{r echo=true}
     png(file = "./meanStepsPerDay.png", width = 480, height = 480)
     hist(stepsPerDay$x, right = FALSE, col="royalblue4", main = "Steps Taken Per Day", xlab = "Steps")
     dev.off()
```

## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
